# -*- coding: utf-8 -*-
"""MLPROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XInrYLAbuCfibvXPqOE07dewY2k137GS
"""

!pip install --upgrade diffusers transformers accelerate torch bitsandbytes scipy safetensors xformers

import torch
from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler
import matplotlib.pyplot as plt
torch.cuda.empty_cache()
model_id = "stabilityai/stable-diffusion-2-1"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
pipe = pipe.to("cuda")
prompt = input()
image = pipe(prompt, width=1000, height=1000).images[0]
plt.imshow(image)
plt.axis('off')
plt.show()

